// ===== DOM References =====

const $ = (sel) => document.querySelector(sel);
const $$ = (sel) => document.querySelectorAll(sel);

export { $, $$ };

export const DOM = {
    sidebarOverlay: $('#sidebar-overlay'),
    sidebar: $('#sidebar'),
    btnMenu: $('#btn-menu'),
    btnNewChat: $('#btn-new-chat'),
    conversationsList: $('#conversations-list'),
    btnSettings: $('#btn-settings'),
    chatTitle: $('#chat-title'),
    modelBadge: $('#model-badge'),
    btnClearChat: $('#btn-clear-chat'),
    chatArea: $('#chat-area'),
    welcomeScreen: $('#welcome-screen'),
    messagesContainer: $('#messages-container'),
    imagePreviewBar: $('#image-preview-bar'),
    imagePreviews: $('#image-previews'),
    btnScrollBottom: $('#btn-scroll-bottom'),
    messageInput: $('#message-input'),
    btnAttach: $('#btn-attach'),
    btnSend: $('#btn-send'),
    btnStop: $('#btn-stop'),
    btnSearch: $('#btn-search'),
    btnDeepResearch: $('#btn-deep-research'),
    fileInput: $('#file-input'),
    settingsOverlay: $('#settings-overlay'),
    settingsPanel: $('#settings-panel'),
    btnCloseSettings: $('#btn-close-settings'),
    btnSaveSettings: $('#btn-save-settings'),
    btnTestConnection: $('#btn-test-connection'),
    connectionStatus: $('#connection-status'),
    btnRefreshModels: $('#btn-refresh-models'),
    btnToggleKey: $('#btn-toggle-key'),
    settingServerUrl: $('#setting-server-url'),
    settingApiKey: $('#setting-api-key'),
    settingModel: $('#setting-model'),
    settingSystemPrompt: $('#setting-system-prompt'),
    settingTemperature: $('#setting-temperature'),
    settingTopP: $('#setting-top-p'),
    settingTopK: $('#setting-top-k'),
    settingMinP: $('#setting-min-p'),
    settingRepeatPenalty: $('#setting-repeat-penalty'),
    settingMaxTokens: $('#setting-max-tokens'),
    settingContextLength: $('#setting-context-length'),
    modelInfo: $('#model-info'),
    // Memory
    settingMemoryEnabled: $('#setting-memory-enabled'),
    settingMemory: $('#setting-memory'),
    memoryTextareaGroup: $('#memory-textarea-group'),
    // Search
    settingSearchEnabled: $('#setting-search-enabled'),
    settingSearxngUrl: $('#setting-searxng-url'),
    searxngUrlGroup: $('#searxng-url-group'),
    settingCrawl4aiUrl: $('#setting-crawl4ai-url'),
    crawl4aiUrlGroup: $('#crawl4ai-url-group'),
    // Settings Labels (cached for performance)
    labelTemp: $('#temperature-value'),
    labelTopP: $('#top-p-value'),
    labelTopK: $('#top-k-value'),
    labelMinP: $('#min-p-value'),
    labelRepeat: $('#repeat-penalty-value'),
    labelMaxTokens: $('#max-tokens-value'),
    labelContextLength: $('#context-length-value'),
    dropZone: $('#drop-zone'),
    toastContainer: $('#toast-container'),
    // Model picker
    modelBadgeText: $('#model-badge-text'),
    modelPicker: $('#model-picker'),
    modelPickerList: $('#model-picker-list'),
    // Models panel
    btnModels: $('#btn-models'),
    modelsOverlay: $('#models-overlay'),
    modelsPanel: $('#models-panel'),
    btnCloseModels: $('#btn-close-models'),
    btnRefreshModelsPanel: $('#btn-refresh-models-panel'),
    modelsListContainer: $('#models-list-container'),
    downloadModelId: $('#download-model-id'),
    downloadQuantization: $('#download-quantization'),
    btnDownloadModel: $('#btn-download-model'),
    downloadStatus: $('#download-status'),
};
